name: Test download

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:


jobs:
    ensure-download:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - run: |
            echo "exit 1" >> micromamba

            sudo cp micromamba /usr/bin/micromamba
            sudo chmod +x /usr/bin/micromamba
        - uses: ./
          with:
            environment-name: test
            create-args: >-
                python
            download-micromamba: true

    ensure-local-default:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - run: |
            curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj bin/micromamba

            sudo cp bin/micromamba /usr/bin/micromamba
            sudo chmod +x /usr/bin/micromamba
        - uses: ./
          with:
            environment-name: test
            create-args: >-
                python
            micromamba-url: https://invalid.domain
